import type { TemplateConfig } from "../types";

export const bundleOfferTemplate: TemplateConfig = {
  id: "bundle_offer",
  name: "Bundle Offer Page",
  structure: ["hero", "product_info", "bundle_pricing", "savings", "features", "reviews", "order", "cta"],
  sections: [
    {
      id: "hero",
      type: "hero_section",
      layout: "centered",
      label: "Hero",
      required: true,
      settings: { textAlign: "center", overlay: 0.3 },
      fields: [
        { key: "hero_title", label: "Title", type: "text", required: true, defaultValue: "Buy More & Save More" },
        { key: "hero_subtitle", label: "Subtitle", type: "textarea", required: false, defaultValue: "Exclusive bundle discounts for a limited time." },
        { key: "hero_ctaText", label: "CTA text", type: "text", required: false, defaultValue: "Get Bundle Deal" },
        { key: "hero_ctaLink", label: "CTA link (empty = no redirect)", type: "text", required: false, placeholder: "#order" },
        { key: "hero_bgImage", label: "Background image URL", type: "image", required: false, placeholder: "https://...", defaultValue: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80" },
      ],
    },
    {
      id: "product_info",
      type: "product_info",
      label: "Product info",
      required: true,
      settings: {
        productInfoMediaStyle: "carousel",
        productInfoImagesFieldKey: "product_info_images",
        carouselMode: "slide",
        carouselIndicators: true,
        carouselControls: true,
        carouselDuration: "700",
        carouselEase: "ease-in-out",
      },
      fields: [
        { key: "product_name", label: "Product name", type: "text", required: true, defaultValue: "Bundle Deal" },
        { key: "product_description", label: "Product description", type: "textarea", required: false, defaultValue: "Exclusive bundle discounts for a limited time. Buy more and save more." },
        { key: "product_info_media_style", label: "Cách hiển thị ảnh", type: "text", required: false, defaultValue: "carousel", options: ["thumbnail", "gallery", "carousel"] },
        { key: "product_thumbnail", label: "Ảnh chính (tùy chọn)", type: "image", required: false, placeholder: "https://...", defaultValue: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80" },
        {
          key: "product_info_images",
          label: "List image",
          type: "image_list",
          required: false,
          values: [
            "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80",
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
          ],
        },
      ],
    },
    {
      id: "bundle_pricing",
      type: "bundle_pricing",
      label: "Bundle pricing",
      required: true,
      fields: [
        { key: "bundle_heading", label: "Section heading", type: "text", required: true, defaultValue: "Choose Your Bundle" },
        { key: "bundle_1_name", label: "Bundle 1 name", type: "text", required: true, defaultValue: "Starter — 1 item" },
        { key: "bundle_1_price", label: "Bundle 1 price", type: "text", required: true, defaultValue: "$29" },
        { key: "bundle_2_name", label: "Bundle 2 name", type: "text", required: false, defaultValue: "Best Value — 3 items" },
        { key: "bundle_2_price", label: "Bundle 2 price", type: "text", required: false, defaultValue: "$69" },
        { key: "bundle_best_value", label: "Best value label", type: "text", required: false, defaultValue: "Best Value" },
      ],
    },
    {
      id: "savings",
      type: "savings",
      label: "Savings",
      required: false,
      fields: [
        { key: "savings_heading", label: "Section heading", type: "text", required: false, defaultValue: "You Save" },
        { key: "savings_amount", label: "Savings amount/text", type: "text", required: false, defaultValue: "Up to 40% when you bundle" },
        { key: "savings_note", label: "Savings note", type: "textarea", required: false, defaultValue: "Compared to buying each item separately. Limited-time bundle pricing." },
      ],
    },
    {
      id: "features",
      type: "features_grid",
      label: "Features",
      required: false,
      settings: { columns: 2, iconSize: "sm", featuresFieldKey: "features" },
      fields: [
        { key: "features_heading", label: "Heading", type: "text", defaultValue: "What's Included" },
        {
          key: "features",
          label: "Features (icon, title, desc)",
          type: "object_list",
          required: false,
          listItemKeys: ["icon", "title", "desc"],
          values: [
            { icon: "✓", title: "Full product set", desc: "Everything you need in one bundle—no extra purchases required." },
            { icon: "✓", title: "Exclusive bundle bonus", desc: "Extra value items only available with this bundle deal." },
          ],
        },
      ],
    },
    {
      id: "reviews",
      type: "review_list",
      label: "Reviews",
      required: false,
      settings: { layout: "list", showStars: true, reviewsFieldKey: "reviews", layoutFieldKey: "review_layout" },
      fields: [
        { key: "reviews_rating", label: "Rating (0–5)", type: "text", required: false, defaultValue: "4.6" },
        { key: "reviews_heading", label: "Title", type: "text", required: false, defaultValue: "Customer Reviews" },
        { key: "review_layout", label: "Cách hiển thị", type: "text", required: false, defaultValue: "list", options: ["list", "slider"] },
        {
          key: "reviews",
          label: "Reviews (rating, comment, author)",
          type: "object_list",
          required: false,
          listItemKeys: ["rating", "comment", "author"],
          values: [
            { rating: "5", comment: "The bundle was a no-brainer. Saved a lot and got more than I expected. Love it.", author: "Sam D." },
            { rating: "4.5", comment: "Best deal I've found. Quality is great across all items. Will buy again.", author: "Taylor M." },
          ],
        },
      ],
    },
    {
      id: "order",
      type: "order_form",
      label: "Order form",
      required: false,
      settings: {
        orderFormFieldsKey: "order_formFields",
        orderWrapperClass: "",
        orderInnerClass: "max-w-md mx-auto rounded-xl border border-gray-200 p-6 bg-gray-50",
        orderTitleClass: "text-2xl font-bold text-gray-900 mb-4",
        orderPromoClass: "text-gray-600 mb-6",
        orderInputClass: "w-full px-3 py-2 border border-gray-300 rounded-lg bg-white text-gray-900",
        orderBtnClass: "w-full py-3 font-semibold rounded-lg bg-green-600 text-white hover:bg-green-700",
        orderLabelClass: "text-gray-700",
      },
      fields: [
        { key: "order_title", label: "Title", type: "text", required: false, defaultValue: "Get the Bundle" },
        { key: "order_promoText", label: "Promo text", type: "textarea", required: false, defaultValue: "Enter your details to secure your bundle deal." },
        { key: "order_buttonText", label: "Button text", type: "text", required: false, defaultValue: "Add to Cart" },
        {
          key: "order_formFields",
          label: "Form fields (order = display order). Each row: key, label, inputType, inputClass (Tailwind, optional)",
          type: "object_list",
          required: false,
          listItemKeys: ["key", "label", "inputType", "inputClass"],
          values: [
            { key: "email", label: "Email", inputType: "email", inputClass: "" },
            { key: "name", label: "Your name", inputType: "text", inputClass: "" },
            { key: "phone", label: "Phone", inputType: "tel", inputClass: "" },
          ],
        },
      ],
    },
    {
      id: "cta",
      type: "cta",
      label: "CTA",
      required: true,
      fields: [
        { key: "cta_heading", label: "CTA heading", type: "text", required: true, defaultValue: "Grab the Bundle" },
        { key: "cta_button", label: "Button text", type: "text", required: true, defaultValue: "Get Bundle Deal" },
        { key: "cta_link", label: "Button link (empty = no redirect)", type: "text", required: false, placeholder: "#order" },
      ],
    },
  ],
};
