import type { TemplateConfig } from "../types";

export const hotTrendProductTemplate: TemplateConfig = {
  id: "hot_trend_product",
  name: "Hot Trend Product Page",
  structure: [
    "hero",
    "product_info",
    "product_viral",
    "features",
    "before_after",
    "reviews",
    "faq",
    "order",
    "footer",
    "sticky_cta",
  ],
  sections: [
    {
      id: "hero",
      type: "hero_section",
      layout: "centered",
      label: "Hero",
      required: true,
      settings: { textAlign: "center", overlay: 0.3, heroVariant: "hot_trend" },
      fields: [
        { key: "hero_title", label: "Title", type: "text", required: true, defaultValue: "Sản phẩm Hot Trend 2026" },
        { key: "hero_subtitle", label: "Subtitle", type: "textarea", required: false, defaultValue: "Giải pháp thông minh giúp cuộc sống dễ dàng hơn" },
        { key: "hero_ctaText", label: "CTA text", type: "text", required: false, defaultValue: "🔥 MUA NGAY - GIẢM 40%" },
        { key: "hero_ctaLink", label: "Link CTA (để trống = không redirect)", type: "text", required: false, placeholder: "#order" },
        { key: "hero_bgImage", label: "Background image URL", type: "image", required: false, placeholder: "https://...", defaultValue: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80" },
      ],
    },
    {
      id: "product_info",
      type: "product_info",
      label: "Thông tin sản phẩm (tên, mô tả, ảnh)",
      required: true,
      settings: {
        productInfoMediaStyle: "carousel",
        productInfoImagesFieldKey: "product_info_images",
        carouselMode: "slide",
        carouselIndicators: true,
        carouselControls: true,
        carouselDuration: "700",
        carouselEase: "ease-in-out",
      },
      fields: [
        { key: "product_name", label: "Tên sản phẩm", type: "text", required: true, defaultValue: "Sản phẩm Hot Trend 2026" },
        { key: "product_description", label: "Mô tả ngắn", type: "textarea", required: false, defaultValue: "Giải pháp thông minh giúp cuộc sống dễ dàng hơn. Chất lượng cao, dễ sử dụng." },
        { key: "product_info_media_style", label: "Cách hiển thị ảnh", type: "text", required: false, defaultValue: "carousel", options: ["thumbnail", "gallery", "carousel"] },
        { key: "product_thumbnail", label: "Ảnh chính (tùy chọn; nếu để trống sẽ dùng ảnh đầu trong danh sách)", type: "image", required: false, placeholder: "https://...", defaultValue: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80" },
        {
          key: "product_info_images",
          label: "List image",
          type: "image_list",
          required: false,
          values: [
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
            "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80",
          ],
        },
      ],
    },
    {
      id: "product_viral",
      type: "product_viral",
      label: "Điểm viral — Lý do sản phẩm hot",
      required: true,
      settings: { viralBulletsFieldKey: "viral_bullets", viralImageFieldKey: "viral_image" },
      fields: [
        { key: "viral_image", label: "Ảnh block viral (để trống hiển thị ô placeholder)", type: "image", required: false, placeholder: "https://..." },
        { key: "viral_heading", label: "Tiêu đề block", type: "text", required: true, defaultValue: "Vì sao sản phẩm này đang viral?" },
        { key: "viral_bullets", label: "Điểm viral (mỗi dòng một ý)", type: "string_list", required: false, values: ["Thiết kế thông minh", "Tiết kiệm thời gian", "Dễ sử dụng cho mọi người", "Chất lượng cao"] },
        { key: "viral_price", label: "Giá hiển thị", type: "text", required: false, defaultValue: "499.000đ" },
        { key: "viral_ctaText", label: "Nút CTA", type: "text", required: false, defaultValue: "ĐẶT HÀNG NGAY" },
        { key: "viral_ctaLink", label: "Link CTA (để trống = không redirect)", type: "text", required: false, placeholder: "#order" },
      ],
    },
    {
      id: "features",
      type: "features_grid",
      label: "Lợi ích vượt trội",
      required: false,
      settings: { columns: 4, iconSize: "lg", featuresFieldKey: "features" },
      fields: [
        { key: "features_heading", label: "Tiêu đề section", type: "text", defaultValue: "Lợi ích vượt trội" },
        {
          key: "features",
          label: "Lợi ích (mỗi ô: icon, title, desc)",
          type: "object_list",
          required: false,
          listItemKeys: ["icon", "title", "desc"],
          values: [
            { icon: "⚡", title: "Tiết kiệm thời gian", desc: "Hoàn thành công việc chỉ trong vài giây" },
            { icon: "🧠", title: "Thiết kế thông minh", desc: "Dễ sử dụng cho mọi đối tượng" },
            { icon: "🛡", title: "Chất lượng cao", desc: "Độ bền cao, sử dụng lâu dài" },
            { icon: "🔥", title: "Hot Trend", desc: "Sản phẩm đang viral trên TikTok" },
          ],
        },
      ],
    },
    {
      id: "before_after",
      type: "image_gallery",
      label: "Trước & Sau khi sử dụng",
      required: false,
      settings: { style: "grid", aspectRatio: "1/1", imagesFieldKey: "images", displayStyleFieldKey: "display_style" },
      fields: [
        { key: "gallery_heading", label: "Tiêu đề section", type: "text", required: false, defaultValue: "Trước & Sau khi sử dụng" },
        { key: "display_style", label: "Cách hiển thị", type: "text", required: false, defaultValue: "grid", options: ["grid"] },
        {
          key: "images",
          label: "List image",
          type: "image_list",
          required: false,
          values: [
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
          ],
        },
      ],
    },
    {
      id: "reviews",
      type: "review_list",
      label: "Khách hàng nói gì",
      required: false,
      settings: { layout: "list", showStars: true, reviewsFieldKey: "reviews", layoutFieldKey: "review_layout" },
      fields: [
        { key: "reviews_rating", label: "Điểm tổng (0–5)", type: "text", required: false, defaultValue: "5" },
        { key: "reviews_heading", label: "Tiêu đề section", type: "text", required: false, defaultValue: "Khách hàng nói gì" },
        { key: "review_layout", label: "Cách hiển thị", type: "text", required: false, defaultValue: "list", options: ["list", "slider"] },
        {
          key: "reviews",
          label: "Review (mỗi ô: rating, comment, author)",
          type: "object_list",
          required: false,
          listItemKeys: ["rating", "comment", "author"],
          values: [
            { rating: "5", comment: "Sản phẩm rất tiện, dùng cực kỳ thích.", author: "Minh Anh" },
            { rating: "5", comment: "Đúng như quảng cáo, đáng tiền.", author: "Tuấn Trần" },
            { rating: "5", comment: "Giao hàng nhanh, chất lượng tốt.", author: "Hải Nguyễn" },
          ],
        },
      ],
    },
    {
      id: "faq",
      type: "faq",
      label: "Câu hỏi thường gặp",
      required: false,
      settings: { expandFirst: false, style: "bordered", faqItemsFieldKey: "faq_items" },
      fields: [
        { key: "faq_heading", label: "Tiêu đề section", type: "text", required: false, defaultValue: "Câu hỏi thường gặp" },
        {
          key: "faq_items",
          label: "FAQ (mỗi ô: q, a)",
          type: "object_list",
          required: false,
          listItemKeys: ["q", "a"],
          values: [
            { q: "Giao hàng bao lâu?", a: "2-5 ngày toàn quốc." },
            { q: "Thanh toán thế nào?", a: "Thanh toán khi nhận hàng (COD)." },
            { q: "Có bảo hành không?", a: "Đổi trả trong 7 ngày nếu lỗi." },
          ],
        },
      ],
    },
    {
      id: "order",
      type: "order_form",
      label: "Đặt hàng",
      required: false,
      settings: {
        buttonColor: "#ef4444",
        buttonTextColor: "#ffffff",
        backgroundColor: "#000000",
        fields: ["name", "phone", "address"],
        inputBackgroundColor: "#ffffff",
        inputTextColor: "#111827",
        inputBorderColor: "#e5e7eb",
      },
      fields: [
        { key: "order_title", label: "Tiêu đề form", type: "text", required: false, defaultValue: "Đặt hàng ngay hôm nay" },
        { key: "order_promoText", label: "Dòng khuyến mãi", type: "textarea", required: false, defaultValue: "Giảm giá 40% chỉ trong hôm nay" },
        { key: "order_buttonText", label: "Chữ nút bấm", type: "text", required: false, defaultValue: "🔥 ĐẶT HÀNG NGAY" },
      ],
    },
    {
      id: "footer",
      type: "footer",
      label: "Footer",
      required: false,
      fields: [
        { key: "footer_text", label: "Nội dung footer", type: "text", required: false, defaultValue: "© 2026 Official Store" },
        { key: "footer_links", label: "Links (cách nhau bằng dấu phẩy)", type: "text", required: false },
      ],
    },
    {
      id: "sticky_cta",
      type: "sticky_cta",
      label: "Sticky CTA",
      required: false,
      fields: [
        { key: "sticky_cta_text", label: "Chữ hiển thị", type: "text", required: false, defaultValue: "🔥 Giảm giá 40% hôm nay - Mua ngay" },
        { key: "sticky_cta_link", label: "Link (tùy chọn)", type: "url", required: false, placeholder: "#order" },
      ],
    },
  ],
};
