import type { TemplateConfig } from "../types";

export const longFormProductTemplate: TemplateConfig = {
  id: "long_form_product",
  name: "Shopify Long Form Product Page",
  structure: ["hero", "product_info", "gallery", "features", "how_it_works", "comparison", "reviews", "ugc", "faq", "shipping", "order", "cta"],
  sections: [
    {
      id: "hero",
      type: "hero_section",
      layout: "two-column",
      label: "Hero",
      required: true,
      settings: { textAlign: "left", overlay: 0.4 },
      fields: [
        { key: "hero_title", label: "Title", type: "text", required: true, defaultValue: "The Only Product You'll Ever Need", style: { fontSize: "1.125rem", fontWeight: "700" } },
        { key: "hero_subtitle", label: "Subtitle", type: "textarea", required: false, defaultValue: "Premium quality with thousands of satisfied users.", style: { className: "text-gray-600", lineHeight: "1.6" } },
        { key: "hero_ctaText", label: "CTA text", type: "text", required: false, defaultValue: "Shop Now" },
        { key: "hero_ctaLink", label: "CTA link (empty = no redirect)", type: "text", required: false, placeholder: "#order" },
        { key: "hero_bgImage", label: "Background image URL", type: "image", required: false, placeholder: "https://...", defaultValue: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=1200&q=80" },
      ],
    },
    {
      id: "product_info",
      type: "product_info",
      label: "Product info",
      required: true,
      settings: {
        productInfoMediaStyle: "carousel",
        productInfoImagesFieldKey: "product_info_images",
        carouselMode: "slide",
        carouselIndicators: true,
        carouselControls: true,
        carouselDuration: "700",
        carouselEase: "ease-in-out",
      },
      fields: [
        { key: "product_name", label: "Product name", type: "text", required: true, defaultValue: "The Only Product You'll Ever Need", style: { fontSize: "1.5rem", fontWeight: "700", color: "#111827" } },
        { key: "product_description", label: "Product description", type: "textarea", required: false, defaultValue: "Premium quality with thousands of satisfied users. Made with the finest materials for lasting durability and comfort.", style: { className: "prose", lineHeight: "1.75" } },
        { key: "product_info_media_style", label: "Cách hiển thị ảnh", type: "text", required: false, defaultValue: "carousel", options: ["thumbnail", "gallery", "carousel"] },
        { key: "product_thumbnail", label: "Ảnh chính (tùy chọn)", type: "image", required: false, placeholder: "https://...", defaultValue: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80" },
        {
          key: "product_info_images",
          label: "List image",
          type: "image_list",
          required: false,
          values: [
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
          ],
        },
      ],
    },
    {
      id: "gallery",
      type: "image_gallery",
      label: "Gallery",
      required: false,
      settings: { style: "grid", aspectRatio: "1/1", imagesFieldKey: "gallery_images", displayStyleFieldKey: "display_style" },
      fields: [
        { key: "gallery_heading", label: "Section heading", type: "text", required: false, defaultValue: "Product Images" },
        { key: "display_style", label: "Cách hiển thị", type: "text", required: false, defaultValue: "grid", options: ["grid"] },
        {
          key: "gallery_images",
          label: "List image",
          type: "image_list",
          required: false,
          values: [
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
          ],
        },
      ],
    },
    {
      id: "features",
      type: "features_grid",
      label: "Features",
      required: false,
      settings: { columns: 3, iconSize: "sm", featuresFieldKey: "features" },
      fields: [
        { key: "features_heading", label: "Heading", type: "text", required: false, defaultValue: "Why Choose Us", style: { textAlign: "center", fontWeight: "600" } },
        {
          key: "features",
          label: "Features (icon, title, desc)",
          type: "object_list",
          required: false,
          listItemKeys: ["icon", "title", "desc"],
          values: [
            { icon: "✓", title: "Premium Quality", desc: "Made with the finest materials for lasting durability and comfort." },
            { icon: "✓", title: "Fast Shipping", desc: "Free standard shipping on all orders. Express delivery available." },
            { icon: "✓", title: "24/7 Support", desc: "Our customer care team is always here to help with any questions." },
          ],
        },
      ],
    },
    {
      id: "how_it_works",
      type: "how_it_works",
      label: "How it works",
      required: false,
      fields: [
        { key: "how_heading", label: "Section heading", type: "text", required: false, defaultValue: "How It Works" },
        { key: "step_1", label: "Step 1", type: "text", required: false, defaultValue: "Add to cart and checkout securely" },
        { key: "step_2", label: "Step 2", type: "text", required: false, defaultValue: "We ship your order within 24 hours" },
        { key: "step_3", label: "Step 3", type: "text", required: false, defaultValue: "Enjoy your product at your doorstep" },
      ],
    },
    {
      id: "comparison",
      type: "comparison",
      label: "Comparison",
      required: false,
      fields: [
        { key: "comparison_heading", label: "Section heading", type: "text", required: false, defaultValue: "Before vs After" },
        { key: "before_text", label: "Before", type: "textarea", required: false, defaultValue: "Struggling with the same old issues. Wasting time and money on solutions that don't work." },
        { key: "after_text", label: "After", type: "textarea", required: false, defaultValue: "Problem solved. Save time, save money, and get results you can see and feel every day." },
      ],
    },
    {
      id: "reviews",
      type: "review_list",
      label: "Reviews",
      required: false,
      settings: { layout: "list", showStars: true, reviewsFieldKey: "reviews", layoutFieldKey: "review_layout" },
      fields: [
        { key: "reviews_rating", label: "Rating (0–5)", type: "text", required: false, defaultValue: "4.2" },
        { key: "reviews_heading", label: "Title", type: "text", required: false, defaultValue: "What Customers Say" },
        { key: "review_layout", label: "Cách hiển thị", type: "text", required: false, defaultValue: "list", options: ["list", "slider"] },
        {
          key: "reviews",
          label: "Reviews (rating, comment, author)",
          type: "object_list",
          required: false,
          listItemKeys: ["rating", "comment", "author"],
          values: [
            { rating: "5", comment: "Exactly what I was looking for. Quality is outstanding and delivery was fast. Highly recommend!", author: "Sarah M." },
            { rating: "4", comment: "Best purchase I've made this year. It really does everything they say. Will buy again.", author: "James K." },
          ],
        },
      ],
    },
    {
      id: "ugc",
      type: "ugc",
      label: "UGC",
      required: false,
      settings: { ugcImagesFieldKey: "ugc_images" },
      fields: [
        { key: "ugc_heading", label: "Section heading", type: "text", required: false, defaultValue: "Real Customers, Real Results" },
        {
          key: "ugc_images",
          label: "List ảnh / video UGC",
          type: "image_list",
          required: false,
          values: [
            "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80",
            "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
          ],
        },
      ],
    },
    {
      id: "faq",
      type: "accordion_faq",
      label: "FAQ",
      required: false,
      settings: { expandFirst: false, style: "bordered", faqItemsFieldKey: "faq_items" },
      fields: [
        { key: "faq_heading", label: "Section heading", type: "text", required: false, defaultValue: "Frequently Asked Questions" },
        {
          key: "faq_items",
          label: "FAQ (q, a)",
          type: "object_list",
          required: false,
          listItemKeys: ["q", "a"],
          values: [
            { q: "How long does shipping take?", a: "We ship within 1–2 business days. Standard delivery is 5–7 days. Express options available at checkout." },
            { q: "What is your return policy?", a: "We offer a 30-day money-back guarantee. If you're not satisfied, return it for a full refund—no questions asked." },
          ],
        },
      ],
    },
    {
      id: "shipping",
      type: "shipping",
      label: "Shipping",
      required: false,
      fields: [
        { key: "shipping_heading", label: "Section heading", type: "text", required: false, defaultValue: "Shipping & Returns" },
        { key: "shipping_text", label: "Shipping info", type: "textarea", required: false, defaultValue: "Free shipping on orders over $50. We ship worldwide. Returns accepted within 30 days. Contact support for exchanges or refunds." },
      ],
    },
    {
      id: "order",
      type: "order_form",
      label: "Order form",
      required: false,
      settings: { buttonColor: "#4F46E5", backgroundColor: "", fields: ["email", "name", "phone"] },
      fields: [
        { key: "order_title", label: "Title", type: "text", required: false, defaultValue: "Place Your Order" },
        { key: "order_promoText", label: "Promo text", type: "textarea", required: false, defaultValue: "Fill in your details and we'll get back to you." },
        { key: "order_buttonText", label: "Button text", type: "text", required: false, defaultValue: "Submit" },
      ],
    },
    {
      id: "cta",
      type: "cta",
      label: "CTA",
      required: true,
      fields: [
        { key: "cta_heading", label: "CTA heading", type: "text", required: true, defaultValue: "Get Yours Today" },
        { key: "cta_button", label: "Button text", type: "text", required: true, defaultValue: "Add to Cart" },
        { key: "cta_link", label: "Button link (empty = no redirect)", type: "text", required: false, placeholder: "#order" },
      ],
    },
  ],
};
